# # # Where things are
source:          .
destination:     ./_site
plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        _data
includes_dir:    _includes
collections:
  pages:
    output: true
    permalink: /:name/index.html
  faqs:
    output: true
  posts:
    output: true

# Handling Reading
safe:                 false
include:
  - .htaccess
  - _pages
exclude:
  - node_modules/
  - package-lock.json
  - package.json
  - webpack.mix.js
  - yarn.lock
  - readme.md
  - shipitfile.js
  - Gemfile
  - Gemfile.lock

keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false


# Plugins
whitelist: []
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
url: "https://johnpuddephatt.github.io"
baseurl: "/yorspace/" # does not include hostname
show_dir_listing: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null
cloudinary: letsdance

quiet:    false
verbose:  true
defaults: []

liquid:
  error_mode: warn

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  false
